spring.application.name=borrower-service

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/loanapplication_db
spring.datasource.username=postgres
spring.datasource.password=raju

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# OCR configuration
ocr.tesseract.enabled=true
ocr.tesseract.datapath=C:/Program Files/Tesseract-OCR/tessdata
ocr.tesseract.language=eng
ocr.tesseract.psm=6

scheduler.loan-monitor.cron=0 5 0 * * *
scheduler.loan-monitor.enabled=true

app.jwt.secret=my-super-secret-key-for-jwt-token-12345678901234567890
app.jwt.expiration-ms=36000000

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true